//This program finds the revenue generated by tickets sold at fixed ticket prices.
#include <iostream>
#include <iomanip>

int main()
{
	const float SEAT_COST_CLASS_A = 15, SEAT_COST_CLASS_B = 12, SEAT_COST_CLASS_C = 9;

	float ticketsSoldClassA, ticketsSoldClassB, ticketsSoldClassC;

	float revenueClassA, revenueClassB, revenueClassC;

	// 10 is an excellent test value
	std::cout << "Hello! Welcome to venue revenue calculator!\n";
	std::cout << "Please enter the number of tickets sold for Class A: ";
	std::cin >> ticketsSoldClassA;
	std::cout << "Please enter the number of tickets sold for Class B: ";
	std::cin >> ticketsSoldClassB;
	std::cout << "Please enter the number of tickets sold for Class C: ";
	std::cin >> ticketsSoldClassC;

	//Finding revenue generated
	revenueClassA = ticketsSoldClassA * SEAT_COST_CLASS_A;
	revenueClassB = ticketsSoldClassB * SEAT_COST_CLASS_B;
	revenueClassC = ticketsSoldClassC * SEAT_COST_CLASS_C;

	//Formatting revenue floats to 2 decimal precision
	std::cout << "Class A Tickets Generated: $" << std::fixed << std::setprecision(2) << revenueClassA << std::endl;
	std::cout << "Class B Tickets Generated: $" << std::fixed << std::setprecision(2) << revenueClassB << std::endl;
	std::cout << "Class C Tickets Generated: $" << std::fixed << std::setprecision(2) << revenueClassC << std::endl;

	return 0;
}